spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max-latest
  
  # Spring应用基本配置
  application:
    name: mxy-browser-use-sample
  
  # 日志配置
  logging:
    level:
      root: INFO
      com.mxy.browser.use: DEBUG
      org.springframework.ai: INFO

# 浏览器配置
browser-use:
  browser:
    headless: false
    keep-alive: false
    disable-security: false
  context:
    window-width: 1280
    window-height: 900
    highlight-elements: true
    viewport-expansion: 0

# 应用程序自定义配置
app:
  task:
    timeout-seconds: 300  # 任务超时时间（秒） 